# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0003_ngouser_fb_token'),
        ('event', '0005_event_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngo.NgoUser')),
            ],
        ),
    ]
