version: '3'

services:

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code/archipelag
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./backend/code:/code

  postgres:
    image: postgres:9.4
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=archipelag
      - POSTGRES_USER=archipelag
      - POSTGRES_DB=archipelag
      - PGPASSWORD=archipelag

volumes:
  postgres-data:
