version: '3'

services:

  backend:
    build: ./backend
    image: hssilesia/archipelag:latest
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend/code:/code
    env_file:
      - .env
    environment:
        - DJANGO_DEBUG=1
    links: [postgres]

  postgres:
    image: postgres:9.4
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=archipelag
      - POSTGRES_USER=archipelag
      - POSTGRES_DB=archipelag
      - PGPASSWORD=archipelag

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env

  maildump:
    image: ball6847/maildump
    ports:
      - 1080:1080

  celery:
    image: hssilesia/archipelag:latest
    command: celery -A archipelag worker -l info
    tty: true
    stdin_open: true
    volumes:
      - ./backend/code:/code
    env_file:
      - .env
    environment:
        - DJANGO_DEBUG=1

volumes:
  postgres-data:
