# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=2048)),
                ('shared', models.URLField(null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market')),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('FB', 'Facebook'), ('IP', 'Informacja Prasowa'), ('NEWS', 'Newsletter'), ('INST', 'Instagram'), ('TW', 'Twitter'), ('SMS', 'SMS Kiss')], default='FB', max_length=4)),
                ('count_hashtag', models.BooleanField(default=True)),
                ('char_restriction', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.MessageType'),
        ),
    ]
