# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('ngo', '0003_ngouser_fb_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FB', 'Facebook'), ('IP', 'Informacja Prasowa'), ('NEWS', 'Newsletter'), ('INST', 'Instagram'), ('TW', 'Twitter'), ('SMS', 'SMS Kiss')], default='FB', max_length=4)),
                ('date_shared', models.DateField()),
                ('visible_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market')),
                ('who_shared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.NgoUser')),
            ],
        ),
    ]
