# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_id_connected_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('SH', 'SHARE'), ('AP', 'ADMIN PROMOTE'), ('RI', 'REGISTER FROM INVITATION'), ('R', 'REGISTER')], default='SH', max_length=2),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
