# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170909_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='ngo.NgoUser'),
            preserve_default=False,
        ),
    ]
