# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_ngouser_fb_token'),
        ('event', '0003_event_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo.NgoUser'),
        ),
    ]
