# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hashtag',
            field=models.CharField(default='', max_length=128),
        ),
    ]
