# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngouser',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
