# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 22:14
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='coins',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
