# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_ngouser_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngouser',
            name='fb_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
