# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='date_ending',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='date_starting',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
